# Generated by Django 5.0.2 on 2024-02-15 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=5)),
                ("is_fiat", models.BooleanField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.FloatField(default=0.0)),
                ("available_balance", models.FloatField(default=0.0)),
                (
                    "account_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="wallet.accounttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("D", "DEPOSIT"), ("W", "WITHDRAWAL"), ("TD", "TRADE"), ("TN", "TRANSFER")]
                    ),
                ),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "PENDING"), ("S", "SUCCESSFUL"), ("F", "FAILED"), ("R", "REFUNDED")]
                    ),
                ),
                ("gateway_ref", models.CharField(max_length=255)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="wallet.wallet")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
