# Generated by Django 5.0.2 on 2024-02-13 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("trader_id", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(blank=True, max_length=12, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("profile_picture", models.ImageField(blank=True, null=True, upload_to="")),
                ("address", models.TextField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female")], null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("two_factor_authentication_enabled", models.BooleanField(default=False)),
                ("hidden_account_balances_toggle_enabled", models.BooleanField(default=False)),
                ("one_click_trade_toggle_enabled", models.BooleanField(default=False)),
                ("one_click_trade_closing_toggle_enabled", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",  # noqa
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
